on:
  push:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DELOYMENT

    strategy:
      matrix:
        node-version: ['20.15.0']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y build-essential python3

      - name: Install package
        run: npm install

      - name: Add .env
        run: echo "${{ secrets.DELOYMENT_ENV }}" >> ./deloyment.env

      - name: Build
        run: npm run build:deloy

      - name: Deloy
        run: sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -r -o StrictHostKeyChecking=no ${{ secrets.PATH }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PATH }}
